import bpy

bl_info = {
    "name": "Fritzing Part Importer",
    "author": "Generated by Copilot",
    "version": (0, 1, 0),
    "blender": (5, 0, 0),
    "location": "File > Import > Fritzing Part (.fzpz/.fzp/.svg)",
    "description": "Import Fritzing part files (.fzpz/.fzp/.svg) into Blender (models and SVGs)",
    "category": "Import-Export",
}

from . import importer

classes = [
    importer.ImportFritzingPart,
    importer.FritzingImporterPanel,
    importer.FritzingImporterPreferences,
]

def register():
    for cls in classes:
        bpy.utils.register_class(cls)
    importer.register_menu()

def unregister():
    importer.unregister_menu()
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)

if __name__ == "__main__":
    register()
